# Generated by Django 3.0.3 on 2020-02-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departing_from', models.CharField(db_index=True, max_length=120)),
                ('destination', models.CharField(db_index=True, max_length=120)),
                ('date_of_departure', models.DateField()),
                ('departure_time', models.TimeField()),
                ('fee', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
