language: python
python:
  - "3.6"

services:
  - postgresql

install:
  - pip install -r requirements.txt

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - coverage run --source='air_reserve/apps' manage.py test && coverage report

after_success:
  - coveralls
