language: python
python:
  - "3.6"

services:
  - postgresql

install:
  - pip3 install -r requirements.txt

before_script:
  - psql -c 'create database test_air_reserve;' -U postgres
  - psql -c "ALTER USER postgres CREATEDB;"

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - coverage run --source='air_reserve/apps/' manage.py test && coverage report

after_success:
  - coveralls
